apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  replicas: 1  # Начальное количество реплик = 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
      - name: scaletestapp
        image: ghcr.io/yandex-practicum/scaletestapp:latest
        imagePullPolicy: Never  # Используем локальный образ
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "10Mi"
            cpu: "100m"
          limits:
            memory: "15Mi"  # Уменьшенный лимит для демонстрации
            cpu: "500m"
        # Health checks для корректной работы HPA
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5 